import { Slate } from 'slates';
import { spec } from './spec';
import {
  listProjects,
  getProject,
  manageProject,
  listIssues,
  manageIssue,
  listMergeRequests,
  manageMergeRequest,
  listPipelines,
  getPipeline,
  runPipeline,
  deletePipeline,
  listJobs,
  manageJob,
  managePipeline,
  getPipelineJobs,
  manageVariables,
  manageEnvironments,
  manageRunners,
  manageSchedules,
  manageTriggers,
  lintCiConfig,
  listDeployments,
  getTestReport,
  browseRepository,
  manageBranch,
  manageFile,
  addComment,
  search,
  createRelease,
  listGroups
} from './tools';
import {
  pushEvents,
  mergeRequestEvents,
  issueEvents,
  pipelineEvents,
  commentEvents,
  deploymentEvents
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listProjects,
    getProject,
    manageProject,
    listIssues,
    manageIssue,
    listMergeRequests,
    manageMergeRequest,
    listPipelines,
    getPipeline,
    runPipeline,
    deletePipeline,
    listJobs,
    manageJob,
    managePipeline,
    getPipelineJobs,
    manageVariables,
    manageEnvironments,
    manageRunners,
    manageSchedules,
    manageTriggers,
    lintCiConfig,
    listDeployments,
    getTestReport,
    browseRepository,
    manageBranch,
    manageFile,
    addComment,
    search,
    createRelease,
    listGroups
  ],
  triggers: [
    pushEvents,
    mergeRequestEvents,
    issueEvents,
    pipelineEvents,
    commentEvents,
    deploymentEvents
  ]
});
